### ISSUE TITLE
mutatePostcode removing space causes no results

### ISSUE THREAD

**Issue by warksit** [Daursu/postcode-lookup#10]
Example postcode: DH6 5EL

`https://maps.googleapis.com/maps/api/geocode/json?address=DH6%205EL&sensor=false&key=[use your own key!]` returns results (notice space in postcode)

`https://maps.googleapis.com/maps/api/geocode/json?address=DH65EL&sensor=false&key=[use your own key!]`returns results correctly

I'm not sure what detrement will be caused by not removing the spaces but will submit a PR doing just that.

**Comment by Daursu** [comment]
I've merged the PR, will close the issue now.
